<?php
return array (
  'shijiazhuang' => 'hebei',
  'taiyuan' => 'shanxi',
  'huhehaote' => 'neimenggu',
  'jinan' => 'shandong',
  'nanjing' => 'jiangsu',
  'hefei' => 'anhui',
  'hangzhou' => 'zhejiang',
  'nanchang' => 'jiangxi',
  'fuzhou' => 'fujian',
  'haikou' => 'hainan',
  'nanning' => 'guangxi',
  'chengdu' => 'sichuan',
  'kunming' => 'yunnan',
  'guiyang' => 'guizhou',
  'lasa' => 'xicang',
  'changsha' => 'hunan',
  'wuhan' => 'hubei',
  'zhengzhou' => 'henan',
  'xian' => 'shaanxi',
  'lanzhou' => 'gansu',
  'xining' => 'qinghai',
  'yinchuan' => 'ningxia',
  'wulumuqi' => 'xinjiang',
  'haerbin' => 'heilongjiang',
  'shenyang' => 'liaoning',
  'changchun' => 'jilin',
  'guangzhou' => 'guangdong',
);
?>